---
# tasks file for galaxy_ng_prerequisites

- name: Install NPM (distro-agnostic)
  package:
    name: npm
    state: present
  retries: "{{ galaxy_ng_package_retries }}"
  register: result
  until: result is succeeded

- block:

  - name: Cloning Ansible Hub UI
    git:
      repo: 'https://github.com/ansible/ansible-hub-ui.git'
      dest: '{{ pulp_user_home }}/ansible-hub-ui'
      force: yes
      version: master
      update: yes
    register: ansible_hub_ui_git
    tags:
      - molecule-idempotence-notest

  - name: Install packages based on package.json
    npm:
      path: '{{ pulp_user_home }}/ansible-hub-ui'

  - name: Building Ansible Hub UI
    command: npm run build-standalone
    args:
      chdir: '{{ pulp_user_home }}/ansible-hub-ui'
    when:
      - ansible_hub_ui_git is defined
      - ansible_hub_ui_git.changed

  become: yes
  become_user: '{{ pulp_user }}'

- name: Creates static dir
  file:
    path: '{{ pulp_webserver_static_dir }}'
    owner: '{{ pulp_user }}'
    group: '{{ pulp_group }}'
    state: directory
    mode: '0775'

- name: Copying Ansible Hub UI to static dir
  copy:
    src: '{{ pulp_user_home }}/ansible-hub-ui/dist/'
    dest: '{{ pulp_webserver_static_dir }}galaxy_ui'
    remote_src: yes
    owner: '{{ pulp_user }}'
    group: '{{ pulp_group }}'
    mode: '0775'
